[package]
name = "invaders_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.crossterm]
version = "0.23.2"
features = ["event-stream"] 
rusty_audio = "1.4.0"
rusty_time = "0.11.3"